# Generated by Django 4.1 on 2022-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faceImage',
            field=models.ImageField(default='facepic.jpg', upload_to='face_pictures'),
        ),
    ]
