# Generated by Django 4.1 on 2022-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_membersince_profile_validto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(default='facepic.jpg', upload_to=''),
        ),
    ]
