# Generated by Django 4.1 on 2022-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_type_of_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type_of_transaction',
            new_name='type_of_member',
        ),
    ]
