# Generated by Django 4.1 on 2022-11-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_type_of_transaction_profile_type_of_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='talla',
            field=models.CharField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE'), ('EXTRA LARGE', 'EXTRA LARGE')], default='MEDIUM', max_length=12),
        ),
    ]
