# Generated by Django 4.1 on 2022-11-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
