# Generated by Django 4.1 on 2022-09-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
