# Generated by Django 4.1 on 2022-09-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0002_rename_events_event_rename_places_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='address',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='description',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='created_date',
            new_name='fecha_creada',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='expiration_date',
            new_name='fecha_expiracion',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='website',
            new_name='sitioweb',
        ),
        migrations.RenameField(
            model_name='benefit',
            old_name='telephone',
            new_name='telefono',
        ),
    ]
