# Generated by Django 4.1 on 2022-09-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0003_rename_address_benefit_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='address',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='website',
            new_name='sitioweb',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='telephone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type_of_place',
            new_name='tipo_de_sitio',
        ),
    ]
