# Generated by Django 4.1 on 2022-09-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0004_rename_address_place_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='fecha_de_evento',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='website',
            new_name='sitioweb',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='telephone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='descrition',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='imagen',
        ),
    ]
