# Generated by Django 4.1 on 2022-09-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0005_rename_address_event_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='imagen',
            field=models.ImageField(default='benefits/benefit.jpg', upload_to='benefits'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(default='events/event.jpg', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagen',
            field=models.ImageField(default='photos/photo.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='place',
            name='imagen',
            field=models.ImageField(default='places/place.jpg', upload_to='places'),
        ),
    ]
