# Generated by Django 4.1 on 2022-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0007_photo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
