# Generated by Django 4.1 on 2022-09-23 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0010_remove_transaction_credit_remove_transaction_debit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.expenseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.incomeaccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_type',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='incometransaction',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.bank'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.bank'),
        ),
    ]
