# Generated by Django 4.1 on 2022-09-23 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0011_expenseaccount_expensetransaction_incomeaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('type_of_transaction', models.CharField(choices=[('IN', 'IN'), ('EX', 'EX')], default='IN', max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.account')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apavelas.bank')),
            ],
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='incometransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='incometransaction',
            name='bank',
        ),
        migrations.DeleteModel(
            name='ExpenseAccount',
        ),
        migrations.DeleteModel(
            name='ExpenseTransaction',
        ),
        migrations.DeleteModel(
            name='IncomeAccount',
        ),
        migrations.DeleteModel(
            name='IncomeTransaction',
        ),
    ]
