# Generated by Django 4.1 on 2022-11-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apavelas', '0014_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
